# print('Hello World')
#print('Merhaba Dünya\nMerhaba Dünya\nHello World\n')
# print('Hello'+ ' ' +'Yağmur')
# print( input('Adın Nedir?'))
# print('Merhaba' + ' ' + input('Adın Ne?'))
# # print(len(input('Hello Whats Your Name?'
# Name = ('Yağmur')
# print(Name)
# Name = ('Nazan')
# # print(Name)
isim = input('Hello Whats Your Name?')
uzunluk = len(isim)
print(uzunluk)